---
title: "Kenya Spur Afrika 2023 - Kickstart Kisumu"
authors: ["Rosalie Lui"]
date: '2022-10-24T08:58:00Z'
categories: Christianity
aliases: null
tags:
- Christianity
- Kenya
- Spur Afrika
- Spur Afrika 2023
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

PRAYER NEEDED: it has come to our attention that we are behind in our fundraising, so therefore there are lots of issues to tackle as well as figuring out what we are doing for the Spur trip in January.

We need to raise *63K* by the end of the year and therefore this has got us worried.  This is due to a range of issues, but one of them is that we have expanded to another office.

So if you can help in any way: please let me know.  I am willing to have a chat with anyone and everyone.

[SpurAfrika Kickstart Kisumu campaign](https://spurafrika.grassrootz.com/kick-start-kisumu)

Update: 

- trying to apply for a PLC grant (so much work for not so much money),
- caught up with Ian and Carolyn to plan our mentors day training (lots of ideas but need time to put it together)
- clinics preparation (need to figure out medications, plus other logistics) 
- I need to do a proper to do list....

[Spur Afrika trip 2023 posts](/spurafrika2023/)
