---
title: Use of mental health treatment plans and disadvantage
date: "2025-05-29"
author: "David Fong"
format: 
  hugo-md:
    code-fold: true
    code-summary: "Show the code"
number-sections: true
toc: true
tags: 
- medicine
- Medicare
- mental health
- mental health treatment plans
- MHTP
- disadvantage
engine: knitr
summary: ""
---

Why does a community health service in Victoria bill relatively few mental health treatment plans (MHTPs), although the practice consults and treats a disproportionately high number of patients with mental health conditions (both high- and low-prevalence, such as schizophrenia and bipolar affective disorder)? Are there barriers to access to mental health care due to socio-economic situation? Is mental health need at times unrelated to provision of mental health care in primary care?

This analysis explores questions of inequity and complexity within a general practice population. It explores the question of what drives the writing and billing MHTPs and whether Medicare (health insurance) billing for mental health care can be distorted reflection of mental health care needs and provision.

Full article in ["Use of mental health treatment plans and disadvantage"](./MHTP.html)

*Photo by <a href="https://unsplash.com/@tex450?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Matthew Ball</a> on <a href="https://unsplash.com/photos/woman-in-black-and-white-long-sleeve-shirt-OJQFlWvUb2E?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>*