---
title: "Dr David Fong's CV"
author: Dr David Fong
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# this code is almost completely based on
#  http://nickstrayer.me/datadrivencv/

# this .Rmd file needs to be adjusted depending on the actual
#  sections of the CV

# to 'auto-build' an .html, a .R file needs to be created in ~/R/build.R
#  with the contents "blogdown::build_dir('static')"
#  as per https://blogdown-demo.rbind.io/2017/09/06/
#    adding-r-markdown-documents-of-other-output-formats/
#
# I further added processing to ~/R/build.R to create a .pdf,
#    based on render_cv.r

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "./assets/datadrivencv/",  #
  pdf_mode = params$pdf_mode,
  resume_mode = FALSE,
  network_mode = FALSE
)

CV_network <- create_CV_object(
  data_location = "./assets/datadrivencv/",  #
  pdf_mode = params$pdf_mode,
  resume_mode = FALSE,
  network_mode = TRUE
)

#

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
  cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```

Aside
================================================================================


```{r warning=FALSE, message=FALSE}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year

#' Build interactive network logo
#'
#' Constructs a network based on your position data to be used as a logo.
#' Interactive in HTML version and static in the PDF version. Notes are entries,
#' colored by section and connected if they occurred in the same year
#'
#' This is a modified version of Nick Strayer's code which creates a more
#' 'sparse' network, by not having redundant connections which span multiple years
#' 
#' @param position_data position data from your `CV_Printer` class.
#' @param sparse only one connection between nodes which overlap for more than one year
#'
#' @return Interactive force-directed layout network of your CV data
#' @export
build_network_logo <- function(position_data, sparse = FALSE){
  
  positions <- position_data %>%
    dplyr::mutate(
      id = dplyr::row_number(),
      title = stringr::str_remove_all(title, '(\\(.+?\\))|(\\[)|(\\])'),
      institution = stringr::str_remove_all(institution, '(\\(.+?\\))|(\\[)|(\\])'),
      section = stringr::str_replace_all(section, "_", " ") %>% stringr::str_to_title()
    ) %>%
    dplyr::mutate(institution = dplyr::if_else(
      institution == "N/A", "", institution
    )) %>%
    dplyr::mutate(
      title = paste0(title, "\n", institution)
    )
  
  combination_indices <- function(n){
    rep_counts <- (n:1) - 1
    dplyr::tibble(
      a = rep(1:n, times = rep_counts),
      b = purrr::flatten_int( purrr::map(rep_counts, ~{tail(1:n, .x)}) )
    )
  }
  current_year <- lubridate::year(lubridate::ymd(Sys.Date()))
  edges <- positions %>%
    dplyr::select(id, start_year, end_year) %>%
    dplyr::mutate(
      end_year = ifelse(end_year > current_year, current_year, end_year),
      start_year = ifelse(start_year > current_year, current_year, start_year)
    ) %>%
    purrr::pmap_dfr(function(id, start_year, end_year){
      dplyr::tibble(
        year = start_year:end_year,
        id = id
      )
    }) %>%
    dplyr::group_by(year) %>%
    tidyr::nest() %>%
    dplyr::rename(ids_for_year = data) %>%
    purrr::pmap_dfr(function(year, ids_for_year){
      combination_indices(nrow(ids_for_year)) %>%
        dplyr::transmute(
          year = year,
          source = ids_for_year$id[a],
          target = ids_for_year$id[b]
        )
    })
  
  if (sparse) {
    # remove multiple edges which are the 'same' connection but different years
    edges <- edges %>%
      dplyr::group_by(source, target) %>%
      dplyr::summarise(year = min(year)) %>%
      dplyr::ungroup()
  }
  
  network_data <- list(nodes = dplyr::select(positions, -in_resume,-timeline),
                       edges = edges) %>%
    jsonlite::toJSON()
  
  # viz_script <- readr::read_file(system.file("js/cv_network.js", package = "datadrivencv"))
  # replaced with slightly customised script, altering forceManyBody() to reduce the strength of repulsion
  # the current CV contains many nodes, resulting in too much 'repulsion' with the default setting
  # see https://www.d3indepth.com/force-layout/
  
  viz_script <- '
  const data_json = document.querySelector("script[type=\'application/json\']").textContent;
const {edges, nodes} = JSON.parse(data_json);

class MyHandler extends Paged.Handler {
	constructor(chunker, polisher, caller) {
		super(chunker, polisher, caller);
	}

	afterRendered (){
		plot_network();
	}
}
Paged.registerHandlers(MyHandler);

function plot_network(){
  const {width, height} = document.querySelector("svg#cv_network_viz").getBoundingClientRect();

  const svg = d3.select("svg#cv_network_viz")
    .attr("width", width)
    .attr("height", height);

  const unique_sections = [...new Set(nodes.map(d => d.section))];
  const color_scale = d3.scaleOrdinal()
    .domain(unique_sections)
    .range(d3.schemeSet2);

  const edge_color = d3.scaleLinear()
    .domain(d3.extent(edges, d => d.year));

  const simulation = d3.forceSimulation(nodes)
    .force("link", d3.forceLink(edges).id(d => d.id))
    .force("charge", d3.forceManyBody().strength(-6))
    .force("center", d3.forceCenter(width / 2, height / 2))
    .on("tick", ticked);

  const g = svg.append("g");

  const link = g
    .selectAll("line")
    .data(edges)
    .enter().append("line")
      .attr("stroke", d => d3.interpolateGreys(edge_color(d.year)))
      .attr("stroke-width", 0.5);

  const node = g
    .attr("stroke", "#fff")
    .attr("stroke-width", 1.5)
    .selectAll("circle")
    .data(nodes)
    .enter().append("circle")
      .attr("r", 5)
      .attr("fill", d => color_scale(d.section))
      .call(drag(simulation));

  node.append("title")
      .text(d => `${d.section}\n${d.title}`);

  svg.call(d3.zoom()
      .extent([[0, 0], [width, height]])
      .scaleExtent([1, 8])
      .on("zoom", zoomed));

  function ticked() {
    link
        .attr("x1", d => d.source.x)
        .attr("y1", d => d.source.y)
        .attr("x2", d => d.target.x)
        .attr("y2", d => d.target.y);

    node
        .attr("cx", d => d.x)
        .attr("cy", d => d.y);
  }

  function zoomed() {
    g.attr("transform", d3.event.transform);
  }

  function drag(simulation){

    function dragstarted(d) {
      if (!d3.event.active) simulation.alphaTarget(0.3).restart();
      d.fx = d.x;
      d.fy = d.y;
    }

    function dragged(d) {
      d.fx = d3.event.x;
      d.fy = d3.event.y;
    }

    function dragended(d) {
      if (!d3.event.active) simulation.alphaTarget(0);
      d.fx = null;
      d.fy = null;
    }

    return d3.drag()
        .on("start", dragstarted)
        .on("drag", dragged)
        .on("end", dragended);
  }

}
'
  
  glue::glue(
    "<script id = \"data_for_network\" type = \"application/json\">",
    "{network_data}",
    "</script>",
    "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/d3/5.16.0/d3.min.js\"></script>",
    "<svg style = \"width: 100%; height:320px; margin-top: -125px;\" id = \"cv_network_viz\"></svg>",
    "<script>",
    "{viz_script}",
    "</script>"
  )
  
}


build_network_logo(CV_network$entries_data, sparse = TRUE)
```


```{r}
if(params$pdf_mode){
  cat("View this CV online with links at _www.davidfong.org/_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://davidfong.netlify.app/CV/cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available [on github.com/DavidPatShuiFong/](https://github.com/DavidPatShuiFong/vkelimHomepage/).

Last updated on `r Sys.Date()`.



Main
================================================================================

Dr David Fong {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```

```{r}
# Research Experience {data-icon=laptop}
# -------------------------------------------------------------------------------- 
# CV %<>% print_section('research_positions')
```

Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('professional_experience_aside')
```
:::

```{r}
CV %<>% print_section('professional_positions')
```

<!-- These breaks just force a new page so section doesn't get cut off -->
<!-- <br> -->

Selected Data Analyses and Contributions {data-icon=chart-line}
--------------------------------------------------------------------------------

::: aside
```{r}
# CV %<>% print_text_block('data_science_writing_aside')
```
:::

```{r}
CV %<>% print_section('data_science_writings')
```

Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('teaching_experience_aside')
```
:::

```{r}
CV %<>% print_section('teaching_positions')
```



```{r}
# Selected Press (About)  {data-icon=newspaper}
# --------------------------------------------------------------------------------

# CV %<>% print_section('about_me_press')
```


<br>
<br>


```{r}
# Selected Press (By)  {data-icon=newspaper}
# --------------------------------------------------------------------------------

# CV %<>% print_section('by_me_press')
```



Publications {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('academic_articles')
```



```{r}
CV %<>% print_links()
```

