---
title: Kenya Spur Afrika 2021 - Returning
author: Rosalie Lui
date: '2022-01-06'
categories:
- Christianity
- Kenya
- Spur Afrika
- Spur Afrika 2021
comments:
  utterances:
    repo: DavidPatShuiFong/vkelimHomepage
    issue-term: post/kenya2021doha2/
    theme: github-dark-orange
---

Hello from Doha!! 👋🖐

We had a little hassle getting checked in at Kenya as we went to the wrong terminal, however after some assistance from Patoh and Sue, we got to the right place. Again, check in wasn't so straight forward with multiple people checking our documents. Thank God we arrived to the airport early! 😍🥰

Anyway, the flight wasn't bad as it was a very nice big plane. Doha airport feels like a luxury after being in Kenya, especially compared to Kisumu airport. I think I am experiencing culture shock already! 😅🤣😂

Please pray for the next stage. Praying our 14 hour flight will be smooth and we get back into Melbourne ok. 

Also, pray that our covid results will come back soon when we arrive. We know there are heaps of issues with covid currently, but I would love to start my new job at Knox on Tuesday. I will have to get my results before starting. David is also starting work on Tuesday so we both would appreciate some prayer. It definitely feels like COVID drama is high in Melbourne. While in Kenya, COVID doesn't really register. I suppose Kenya doesn't have the resources to. Their vaccination rate in Kenya is also terribly low. 🥴😷

Sorry, it's a long post. More and more thoughts will come to me soon. Hopefully I can share with you all in person one day.

Stay Safe! We shall keep you updated when we arrive in Melbourne. 😆😁

[Spur Afrika trip 2021-2022 posts](/spurafrika2021/)
